language: python

dist: xenial

env:
  global:
    - TEST_DIR=/tmp/iced
    - CACHED_BUILD_DIR="cached"

matrix:
  include:
    # Ubuntu 14.04 versions
    - name: "Python 2.7"
      env: TEST=TRUE NUMPY_VERSION=1.16 SCIPY_VERSION=0.19 COVERAGE=true
    - name: "Python 3.6"
      python: 3.6
      env: TEST=TRUE NUMPY_VERSION=1.16 SCIPY_VERSION=0.19 COVERAGE=true
    - name: "Python 3.6 new"
      python: 3.6
      env: TEST=TRUE NUMPY_VERSION=1.17 SCIPY_VERSION=1.3.1 COVERAGE=true
    - name: "Python 3.7"
      python: 3.7
      env: TEST=TRUE COVERAGE=true NUMPY_VERSION=1.17 SCIPY_VERSION=1.3
    - name: "Python 3.8"
      python: 3.8
      env: TEST=TRUE COVERAGE=true NUMPY_VERSION=* SCIPY_VERSION=*

install: 
    - source build_tools/travis/install.sh

before_script:
    - make clean

script:
    - bash build_tools/travis/test_script.sh

after_success:
    # Ignore coveralls failures as the coveralls server is not very reliable
    # but we don't want travis to report a failure in the github UI just
    # because the coverage report failed to be published.
    # coveralls need to be run from the git checkout
    # so we need to copy the coverage results from TEST_RUN_FOLDER
    - bash build_tools/travis/after_success.sh 
